---
- hosts: all
  gather_facts: true
  become: true
  vars:
    - host_domain: "lab.local"
  tasks:
  - hostname: name={{ inventory_hostname | lower }}.{{ host_domain | lower }}
  - file: src=/usr/share/zoneinfo/Australia/Perth dest=/etc/localtime state=link force=yes
  - apt: update_cache=yes
    when: ansible_os_family == "Debian"
