---
galaxy_info:
  role_name: rsyslogcli_anon
  author: Andrew Milne
  description: Configure rsyslog client to send logs to anonymous TLS server.
  license: license (GPLv2)

  min_ansible_version: 2.8
